---
- name: Listen for events from dhcp
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001     
  rules:
    - name: Handle event from dhcp service
      condition: event.payload is search("dhcpd",ignorecase=true) 
             and event.payload is search("DHCPREQUEST",ignorecase=true)
      action:
#        debug:
#          msg: "Received: {{ event.payload }}"
        run_job_template:
          name: Send Mail to alert rogue DHCP 
          organization: "Default"
          job_args:
            extra_vars:
              mailbody: "{{ event.payload }}"
