---
- name: Testing
  hosts: localhost
  sources:
    - name: Load default vars
      ansible.eda.generic:
        payload_file: "./04223505_var.yml"
        display: false
        loop_count: 2000
        loop_delay: 3
