---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
     - ansible.eda.url_check:
        urls:
          - https://aeladawy-aap24-eda.example.com
        delay: 10

  rules:
    - name: Handle Critical Hosts
      condition: event.message == '"status":"CRITICAL"'
      actions:
        - debug:
            msg: "Critical issue detected on host"
