---
- name: Listen for events on a webhook
  hosts: localhost
  sources:
     - ansible.eda.url_check:
        urls:
          - https://google.com
        delay: 10
        verify_ssl: false
  rules:
    - name: Handle Critical Hosts
      condition: event.url_check.status == "up"
      actions:
        - debug:
            msg: "Critical issue detected on host"
